<?php
/**
 * @var $this \Content\Page\RenderObject
 * @var $block \Content\Page\Html\Head
 */
?>
<!DOCTYPE html>
<html lang="<?php echo $block->getLang(); ?>">
<head>
    <meta charset="UTF-8">
    <title><?php echo $block->getPageTitle(); ?></title>

    <link rel="icon" href="<?php echo $block->getPageIcon(); ?>" sizes="32x32" />

    <?php
    foreach ($block->getAdditionalLinkTags() as $tag)
    {
        echo "<link rel='$tag[0]' href='$tag[1]' />\n\t";
    }

    echo "\n\t";

    foreach ($block->getAdditionalScriptTags() as $tag)
    {
        echo "<script type='$tag[0]' src='$tag[1]'></script>\n\t";
    }
    ?>

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="<?php echo $block->getMeta('description'); ?>" />
    <meta name="keywords" content="<?php echo $block->getMeta('keywords'); ?>" lang="<?php echo $block->getLang(); ?>" />

    <?php
    foreach ($block->getAdditionalMetaTags() as $tag)
    {
        echo "<meta name='$tag[0]' content='$tag[1]' lang='{$block->getLang()}'/>\n\t";
    }
    ?>

</head>
