<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8">
    <title>$title</title>
    $script
    <!--<link rel="icon" href="<?= BASE_URL ?>img/csgobeast_steam_pic_1.png" sizes="32x32" />-->
    <!--<link rel="stylesheet" href="<?= BASE_URL ?>styles/styles.css" type="text/css" media="all" />-->
    <!--<script src="<?= BASE_URL ?>scripts/features.js" type="text/javascript"></script>-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>